apiVersion: batch/v1
kind: Job
metadata:
  name: icolcap-job
  namespace: mediacorr
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: icolcap
        image: mediacorr-icolcap:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "app.icolcap"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mediacorr-pvc
