apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mediacorr-api-role
  namespace: mediacorr
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
