apiVersion: v1
kind: Service
metadata:
  name: mediacorr-api
  namespace: mediacorr
spec:
  type: NodePort
  selector:
    app: mediacorr-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
