apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mediacorr-job-runner-binding
  namespace: mediacorr
subjects:
- kind: ServiceAccount
  name: mediacorr-api-sa
  namespace: mediacorr
roleRef:
  kind: Role
  name: mediacorr-job-runner
  apiGroup: rbac.authorization.k8s.io
