apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediacorr-api
  namespace: mediacorr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediacorr-api
  template:
    metadata:
      labels:
        app: mediacorr-api
    spec:
      serviceAccountName: mediacorr-api-sa
      containers:
      - name: api
        image: 813469362433.dkr.ecr.us-east-1.amazonaws.com/mediacorr-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ECR_REGISTRY
          value: "813469362433.dkr.ecr.us-east-1.amazonaws.com"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mediacorr-pvc
