apiVersion: v1
kind: Service
metadata:
  name: mediacorr-api
  namespace: mediacorr
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8000"
spec:
  type: LoadBalancer
  selector:
    app: mediacorr-api
  ports:
  - port: 80
    targetPort: 8000
